# Generated by Django 4.0.1 on 2022-01-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='AutoPayEnabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='BestOfferEnabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
