# Generated by Django 4.0.1 on 2022-01-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_category_autopayenabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='AutoPayEnabled',
        ),
        migrations.RemoveField(
            model_name='category',
            name='BestOfferEnabled',
        ),
    ]
